
jobs:
- job: extract_iso
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      make
      mkdir $BUILD_ARTIFACTSTAGINGDIRECTORY/android-x86/

      # For VHDs
      cp system.sfs $BUILD_ARTIFACTSTAGINGDIRECTORY/android-x86/
      cp initrd.img $BUILD_ARTIFACTSTAGINGDIRECTORY/android-x86/
      cp ramdisk.img $BUILD_ARTIFACTSTAGINGDIRECTORY/android-x86/

      # For Docker
      cp system.tar $BUILD_ARTIFACTSTAGINGDIRECTORY/android-x86/
      cp initrd.tar $BUILD_ARTIFACTSTAGINGDIRECTORY/android-x86/
      cp ramdisk.tar $BUILD_ARTIFACTSTAGINGDIRECTORY/android-x86/

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/android-x86'
      artifactName: android-x86
    displayName: Publish android-x86

- job: kernel
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      apt list --installed | grep java
      apt list --installed | grep jdk

      sudo apt-get remove -y openjdk-11-jre openjdk-11-jdk openjdk-11-jdk-headless
      sudo apt-get remove -y openjdk-10-jre openjdk-10-jdk openjdk-10-jdk-headless
      sudo apt-get remove -y openjdk-9-jre openjdk-9-jdk openjdk-9-jdk-headless
      sudo apt-get remove -y openjdk-7-jre openjdk-7-jdk openjdk-7-jdk-headless
      sudo apt-get install -y repo bc openjdk-8-jdk

      apt list --installed | grep java
      apt list --installed | grep jdk
      apt list --installed | grep jre

      update-java-alternatives --list
      sudo update-java-alternatives -s java-1.8.0-openjdk-amd64

      which javac
      javac -version

      which java
      java -version
    displayName: Install dependencies

  - script: |
      git config --global user.email "Azure Pipelines"
      git config --global user.name "docker-android-x86@github.com"

      ./make-kernel.sh
    displayName: Clone the Android repo

  - script: |
      cd android-x86

      make kernel TARGET_PRODUCT=android_x86_64
      mkdir -p $BUILD_ARTIFACTSTAGINGDIRECTORY/kernel/
      cp out/target/product/x86_64/kernel $BUILD_ARTIFACTSTAGINGDIRECTORY/kernel/
    displayName: Build the Android kernel

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/kernel/'
      artifactName: kernel
    displayName: Publish kernel

- job: build_vhd
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo apt-get install -y qemu-utils

      sudo ./make-vhd.sh

      mkdir -p $BUILD_ARTIFACTSTAGINGDIRECTORY/vhd
      cp android-x86.tar.gz $BUILD_ARTIFACTSTAGINGDIRECTORY/vhd
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/vhd'
      artifactName: vhd
    displayName: Publish vhd
